AWSTemplateFormatVersion: '2010-09-09'
Description: Alarms for Mq source connector.

Parameters:
  IamBoundaryPolicyName:
    Type: String
    Default: ccoe/js-developer
    AllowedPattern: '[a-zA-Z0-9-\/.]+'
  StackName:
    Type: String


Resources:
  RunningTask:
    Type: AWS::CloudWatch::Alarm
    Properties:
        AlarmName: Running Task Mq Source Alaram
        ActionsEnabled: true
        OKActions:
            - Fn::ImportValue: SNS::sns--sss-connect-clusters::Name
        AlarmActions:
            - Fn::ImportValue: SNS::sns--sss-connect-clusters::Name
        MetricName: running
        Namespace: KafkaConnect/Watcher
        Statistic: Sum
        Dimensions:
            - Name: ConnectCluster
              Value: connect.prod.sss.sc.js-devops.internal_8083
            - Name: environment
              Value: prod
            - Name: name
              Value: sc-sss-prod
            - Name: ConnectorName
              Value: MQSource
        Period: 60
        EvaluationPeriods: 1
        DatapointsToAlarm: 1
        Threshold: 1
        ComparisonOperator: LessThanThreshold
        TreatMissingData: breaching

  FailedTask:
    Type: AWS::CloudWatch::Alarm
    Properties:
        AlarmName: Failed MQ Source Alarm
        ActionsEnabled: true
        OKActions:
            - Fn::ImportValue: SNS::sns--sss-connect-clusters::Name
        AlarmActions:
            - Fn::ImportValue: SNS::sns--sss-connect-clusters::Name
        MetricName: failed
        Namespace: KafkaConnect/Watcher
        Statistic: Sum
        Dimensions:
            - Name: ConnectCluster
              Value: connect.prod.sss.sc.js-devops.internal_8083
            - Name: environment
              Value: prod
            - Name: name
              Value: sc-sss-prod
            - Name: ConnectorName
              Value: MQSource
        Period: 60
        EvaluationPeriods: 1
        DatapointsToAlarm: 1
        Threshold: 1
        ComparisonOperator: GreaterThanThreshold
        TreatMissingData: notBreaching
